services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    restart: unless-stopped

  rag-api:
    build: ./rag-api
    container_name: rag-api
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8088:8088"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  qdrant_data:
