services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
    restart: unless-stopped

  rag-api:
    build: ./rag-api
    container_name: rag-api
    env_file:
      - .env
    depends_on:
      - qdrant
    ports:
      - "8088:8088"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3001:8080"
    environment:
      - OPENAI_API_BASE_URL=http://192.168.1.77:8088
      - OPENAI_API_KEY=dummy-key-not-needed
      - WEBUI_SECRET_KEY=paperless-rag-secret-key-2024
      - WEBUI_NAME=Paperless Document Assistant
      - DEFAULT_MODELS=paperless-rag
    volumes:
      - open-webui-data:/app/backend/data
    restart: unless-stopped
    depends_on:
      - rag-api

volumes:
  qdrant_data:
  open-webui-data:
